name: flutterx
description: Flutter &amp; Dart extenction methods
version: 0.0.1
author: Laxman Bhattarai <erluxman@gmail.com>
homepage: https://github.com/erluxman/flutterX
issue_tracker: https://github.com/erluxman/flutterX

environment:
  sdk: ">2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
