name: flutterx
description: Flutter &amp; Dart extenction methods making flutter even more easier and fun
version: 0.0.1
author:
homepage:

environment:
  sdk: ">2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
